//export const LOAD_USERS_REQUEST= 'LOAD_USERS_REQUEST';
export const LOAD_USERS_SUCCESS= 'LOAD_USERS_SUCCESS';
export const LOAD_USER_BY_ID= 'LOAD_USER_BY_ID';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER'; 
export const UPDATE_USER = 'UPDATE_USER'; 
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const LIST_USERS = 'LIST_USERS';
export const CHECK_USERNAME_SUCCESS = 'CHECK_USERNAME_SUCCESS';

export const SERVICE_REQUEST = 'SERVICE_REQUEST_PENDING';
export const SERVICE_REQUEST_ERROR = 'SERVICE_REQUEST_ERROR';
